-- LehrerMaps uses SQLite.
--
-- The authoritative, idempotent schema is initialized automatically by
-- server/db.js when the backend starts. No separate database server or manual
-- schema import is required.
